### PR TITLE
changed incorrect variable on live production

### LINKED ISSUE #125: reset password adjustment
Password reset is not functioning on live production site, will look into it

### PR DESCRIPTION
**Pull request by KizeKaze**
fixes #125

### CODE REVIEW

File: enter_email.php [hunk 1]
```diff
@@ -42,8 +42,8 @@
      $headers = "From: Admin@rayxproject.com" . "\r\n";
      $headers .= "MIME-Version: 1.0\r\n";
      $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
-
-     $msg = "Hi there, click on this <a href=\"http://localhost:9001/new_pass_logic.php?token=" . $token . "\">link</a> to reset your password on rayxproject.com";
+    // localhost for local sided emailing, rayxproject for live production
+     $msg = "Hi there, click on this <a href=\"http://www.rayxproject.com/new_pass_logic.php?token=" . $token . "\">link</a> to reset your password on rayxproject.com";
```
Comment (tony1542) [inline enter_email.php:46]: I believe you can use `$_SERVER['HTTP_HOST']` here so that it'll be localhost when testing locally, and your actual URL when it is live

**Review by tony1542 — APPROVED** [review]
